# Step 4: Send energy to the village

from hydro_lib import *

hydro = Hydro(5)

print("Ready...")

while True:
    # Check if we have enough water in the reservoir
    water_level_ok = not hydro.water_level_low_switch.is_pressed
    if water_level_ok:
        hydro.water_level_led.off()
    else:
        hydro.water_level_led.on()

    if hydro.on_off_switch.is_pressed:
        # Power switch is on
        hydro.power_led.on()
        
        # Only pump if there is enough water in the reservoir
        if water_level_ok:
            hydro.pump_on()
        else:
            hydro.pump_off()

        # Get the energy generated by the turbine and send it to the village
        energy = hydro.get_energy() 
        hydro.show(energy)
        hydro.send_energy(energy)  

    else:
        # Power switch is off
        hydro.power_led.off()
        hydro.show("OFF")
        hydro.pump_off()

    sleep(0.5)
